const sb=window.createChikClient();let user=null,profile=null,dashboardPromise=null,authBusy=false;
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=n=>`৳${Number(n||0).toLocaleString('en-BD')}`;
const cleanEmail=v=>String(v||'').trim().toLowerCase();
const authQuery=new URLSearchParams(location.search),authHash=new URLSearchParams(location.hash.replace(/^#/,'')||'');
let authErrorCode=authQuery.get('error_code')||authQuery.get('error')||authHash.get('error_code')||authHash.get('error')||'';
const authErrorDescription=authQuery.get('error_description')||authHash.get('error_description')||'';
let verificationRequested=authQuery.get('verified')==='1'||authQuery.get('type')==='signup'||authHash.get('type')==='signup';
const recoveryRequested=()=>authQuery.get('type')==='recovery'||authHash.get('type')==='recovery';
const verificationEmailKey='chikchik-pending-verification-email';
const pendingVerificationEmail=()=>{try{return cleanEmail(localStorage.getItem(verificationEmailKey)||'')}catch{return ''}};
const safeAuthError=error=>{const code=String(error?.code||'').toLowerCase(),message=String(error?.message||'').toLowerCase();if(code.includes('email_not_confirmed')||message.includes('email not confirmed'))return 'Please verify your email before signing in.';if(code.includes('invalid')||code.includes('credential')||code.includes('password'))return 'Sign in failed. Check your email and password.';if(code.includes('already')||code.includes('duplicate')||code.includes('unique'))return 'Those account details are already in use. Try a different email, phone or username.';if(code.includes('rate'))return 'Too many attempts right now. Please wait a moment and try again.';return 'We could not complete that request. Please check your details and try again.'};
const safeDataError=error=>{const code=String(error?.code||'').toLowerCase();if(code.includes('duplicate')||code.includes('unique'))return 'That username or phone number is already in use.';return 'We could not save those changes. Please check your details and try again.'};
function setBusy(form,busy,label){form?.querySelectorAll('button[type="submit"]').forEach(button=>{button.disabled=busy;if(label&&!button.dataset.defaultLabel)button.dataset.defaultLabel=button.querySelector('span')?.textContent||button.textContent;const span=button.querySelector('span');if(span)span.textContent=busy?label:button.dataset.defaultLabel||span.textContent})}
const normalizePhone=p=>{let v=String(p||'').replace(/\D/g,'');if(v.startsWith('00880'))return `0${v.slice(5)}`;if(v.startsWith('880'))return `0${v.slice(3)}`;return v};
const hierarchy={'Dhaka North City Corporation':['Ward 1–10','Ward 11–20','Ward 21–30','Uttara','Sector 1','Sector 3','Sector 4','Sector 7','Sector 9','Sector 11','Sector 12','Sector 13','Sector 14','Airport','Diabari','Mirpur','Pallabi','Rupnagar','Gulshan','Banani','Badda','Mohakhali','Mohammadpur','Adabor','Shyamoli','Bashundhara'],'Dhaka South City Corporation':['Ward 1–10','Ward 11–20','Ward 21–30','Dhanmondi','Kalabagan','Hazaribagh','Khilgaon','Mugdapara','Jatrabari','Dania','Motijheel','Paltan','Lalbagh','Wari','Sutrapur'],Dhamrai:['Amta','Balia','Bhararia','Dhamrai','Gangutia','Jadabpur','Kulla','Mahmudabad','Nannar','Rowail','Sanora','Sutipara'],Dohar:['Bilaspur','Kusumhati','Mahmudpur','Muksudpur','Narayanganpur','Nayabari','Raipara','Sutarpara'],Keraniganj:['Aganagar','Basta','Hazratpur','Kalatiya','Kalindi','Konda','Ruhitpur','Sakta','Subhadya','Taranagar','Tegharia'],Nawabganj:['Agla','Bakshanagar','Bandura','Barrah','Churain','Galimpur','Jantrail','Joykrishnapur','Kalakopa','Khalpar','Nayansree','Shikaripara'],Savar:['Aminbazar','Ashulia','Banagram','Bongaon','Dhamsona','Kaundia','Pathalia','Savar','Shimulia','Tetuljhora','Vakurta','Yearpur']};
function setupHierarchy(upId,unionId,selectedUp='',selectedUnion=''){const up=$(`#${upId}`),un=$(`#${unionId}`);if(!up)return;up.innerHTML='<option value="">Upazila / city corporation</option>'+Object.keys(hierarchy).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');up.value=selectedUp||'';const fill=()=>{un.innerHTML='<option value="">Union / ward / local area</option>'+((hierarchy[up.value]||[]).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join(''));un.value=selectedUnion||''};up.onchange=fill;fill()}
function msg(id,text,ok=false){const el=$(`#${id}`);if(!el)return;el.textContent=text;el.className='form-message '+(ok?'ok':'error')}
function hideAuthCallback(){const state=$('#auth-callback-state');if(state){state.hidden=true;state.innerHTML=''}}
function showAuthCallback(kind='pending',email=''){
  const state=$('#auth-callback-state'),tabs=$('.auth-tabs'),loginForm=$('#login-form'),signupForm=$('#signup-form'),recoveryForm=$('#recovery-form');
  if(!state)return;
  email=cleanEmail(email||pendingVerificationEmail());
  if(tabs)tabs.hidden=true;
  if(loginForm)loginForm.hidden=true;
  if(signupForm)signupForm.hidden=true;
  if(recoveryForm)recoveryForm.hidden=true;
  const copy={
    pending:{eyebrow:'One last step',title:'Check your <span>inbox.</span>',body:'Your ChikChik account is created. Open the confirmation link in your email to verify it, then come back here to sign in.',className:'pending'},
    success:{eyebrow:'Email verified',title:'You are <span>all set.</span>',body:'Your email has been verified successfully. Sign in with your password to continue.',className:'success'},
    error:{eyebrow:'Verification link issue',title:'Let’s get you <span>back in.</span>',body:'This verification link is invalid, expired or already used. Request a fresh link below, then check your inbox again.',className:'error'},
    unverified:{eyebrow:'Email verification needed',title:'Verify your <span>email first.</span>',body:'Your password is not changed. Confirm your email from the latest message, then sign in.',className:'error'}
  }[kind]||null;
  const view=copy||{eyebrow:'Account access',title:'Something went <span>wrong.</span>',body:'We could not complete this verification. Please try again from a fresh email link.',className:'error'};
  state.className=`auth-callback ${view.className}`;
  state.innerHTML=`<p class="step-eyebrow">${view.eyebrow}</p><h2>${view.title}</h2><p class="muted">${view.body}</p>${kind!=='success'?`<div class="callback-resend"><label for="verification-email">Email address</label><input id="verification-email" type="email" autocomplete="email" value="${esc(email)}" placeholder="you@example.com"><button type="button" class="btn red" data-resend-verify>Send verification email <b aria-hidden="true">↗</b></button><div id="verification-message" class="form-message" role="status" aria-live="polite"></div></div>`:''}<div class="callback-actions"><button type="button" class="btn outline" data-auth-back>Back to sign in</button>${kind==='success'?'<button type="button" class="btn red" data-auth-success>Sign in now <b aria-hidden="true">↗</b></button>':''}</div>`;
  state.hidden=false;
  state.querySelector('[data-auth-back]')?.addEventListener('click',()=>showAuth('login'));
  state.querySelector('[data-auth-success]')?.addEventListener('click',()=>showAuth('login'));
  state.querySelector('[data-resend-verify]')?.addEventListener('click',async()=>{
    const input=state.querySelector('#verification-email'),button=state.querySelector('[data-resend-verify]'),address=cleanEmail(input?.value);
    if(!input?.checkValidity()||!address){input?.reportValidity();return}
    button.disabled=true;button.querySelector('b')?.remove();button.firstChild.textContent='Sending…';
    try{const {error}=await sb.auth.resend({type:'signup',email:address,options:{emailRedirectTo:window.chikchikAuthUrl('account.html?verified=1')}});msg('verification-message',error?'We could not send a new verification email right now. Please try again later.':'If that account is awaiting verification, a fresh link has been sent.',!error);if(!error)try{localStorage.setItem(verificationEmailKey,address)}catch{}}
    catch{msg('verification-message','We could not send a new verification email right now. Please try again later.')}
    finally{button.disabled=false;button.firstChild.textContent='Send verification email ';}
  });
  if(verificationRequested&&!recoveryRequested()){history.replaceState(null,document.title,window.chikchikAuthUrl(authErrorCode?'account.html':'account.html?verified=1'))}
}
function showAuth(tab,focus=true){const signup=tab==='signup',loginForm=$('#login-form'),signupForm=$('#signup-form'),recoveryForm=$('#recovery-form'),tabs=$('.auth-tabs');if(!loginForm||!signupForm)return;verificationRequested=false;authErrorCode='';history.replaceState(null,document.title,window.chikchikAuthUrl(`account.html?mode=${signup?'signup':'login'}`));hideAuthCallback();if(tabs)tabs.hidden=false;loginForm.hidden=signup;signupForm.hidden=!signup;if(recoveryForm)recoveryForm.hidden=true;$('#auth-view')?.setAttribute('data-auth-mode',tab);document.querySelectorAll('[data-auth-tab]').forEach(b=>{const active=b.dataset.authTab===tab;b.classList.toggle('active',active);if(b.getAttribute('role')==='tab')b.setAttribute('aria-selected',String(active))});if(focus)setTimeout(()=>{const target=signup?signupForm:loginForm;target.querySelector('input:not([type="hidden"])')?.focus({preventScroll:true})},180)}
function showRecovery(){const loginForm=$('#login-form'),signupForm=$('#signup-form'),recoveryForm=$('#recovery-form'),tabs=$('.auth-tabs');if(!loginForm||!signupForm||!recoveryForm)return;hideAuthCallback();if(tabs)tabs.hidden=true;loginForm.hidden=true;signupForm.hidden=true;recoveryForm.hidden=false;$('#auth-view')?.setAttribute('data-auth-mode','recovery');setTimeout(()=>$('#recovery-password')?.focus({preventScroll:true}),180)}
document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>showAuth(b.dataset.authTab));
document.querySelectorAll('[data-toggle-password]').forEach(button=>button.onclick=()=>{const input=$(`#${button.dataset.togglePassword}`);if(!input)return;const visible=input.type==='text';input.type=visible?'password':'text';button.textContent=visible?'Show':'Hide';button.setAttribute('aria-label',visible?'Show password':'Hide password')});
setupHierarchy('account-upazila','account-union');
const navToggle=$('.menu-toggle');navToggle?.addEventListener('click',()=>{const nav=document.querySelector('.nav nav');const open=nav?.classList.toggle('open');navToggle.setAttribute('aria-expanded',String(Boolean(open)))});
$('#signup-form').onsubmit=async e=>{e.preventDefault();if(authBusy)return;const form=e.target,d=Object.fromEntries(new FormData(form));const email=cleanEmail(d.email),phone=normalizePhone(d.phone);if(!form.checkValidity()){form.reportValidity();return}if(!/^01\d{9}$/.test(phone)){msg('signup-message','Enter a valid Bangladesh mobile number, such as 01XXXXXXXXX.');return}authBusy=true;setBusy(form,true,'Creating account…');msg('signup-message','');try{try{localStorage.setItem(verificationEmailKey,email)}catch{}const check=await sb.rpc('is_phone_available',{p_phone:phone});if(check.error){msg('signup-message','We could not validate that phone number right now. Please try again.');return}if(check.data===false){msg('signup-message','That phone number is already linked to an account.');return}const {data,error}=await sb.auth.signUp({email,password:d.password,options:{emailRedirectTo:window.chikchikAuthUrl('account.html?verified=1'),data:{full_name:String(d.full_name||'').trim(),username:String(d.username||'').trim().toLowerCase(),phone,upazila:d.upazila,union_name:d.union_name||'',street_address:String(d.street_address||'').trim()}}});if(error){msg('signup-message',safeAuthError(error));return}if(!data.user){showAuthCallback('pending',email);return}if(data.session){const {error:pe}=await sb.from('profiles').upsert({id:data.user.id,email:data.user.email,phone,full_name:String(d.full_name||'').trim(),username:String(d.username||'').trim().toLowerCase(),division:'Dhaka',district:'Dhaka',upazila:d.upazila,union_name:d.union_name||null,street_address:String(d.street_address||'').trim()});if(pe){msg('signup-message','Your account was created, but the profile could not be saved. Please sign in again.');return}await loadDashboard(data.session.user);msg('signup-message','Account created.',true)}else showAuthCallback('pending',email)}catch(error){msg('signup-message',safeAuthError(error))}finally{authBusy=false;setBusy(form,false)}};
$('#login-form').onsubmit=async e=>{e.preventDefault();if(authBusy)return;const form=e.target,d=Object.fromEntries(new FormData(form));if(!form.checkValidity()){form.reportValidity();return}authBusy=true;setBusy(form,true,'Signing in…');msg('login-message','');try{const {data,error}=await sb.auth.signInWithPassword({email:cleanEmail(d.email),password:d.password});if(error){if(String(error.code||'').toLowerCase().includes('email_not_confirmed')||String(error.message||'').toLowerCase().includes('email not confirmed'))showAuthCallback('unverified',cleanEmail(d.email));else msg('login-message',safeAuthError(error));return}await loadDashboard(data.user)}catch(error){msg('login-message',safeAuthError(error))}finally{authBusy=false;setBusy(form,false)}};
async function loadDashboard(u){
  if(!u)return;
  if(dashboardPromise)return dashboardPromise;
  dashboardPromise=(async()=>{
    user=u;
    void sb.rpc('claim_guest_orders_for_user');
    const {data:p,error}=await sb.from('profiles').select('id,full_name,username,email,phone,division,district,upazila,union_name,street_address').eq('id',u.id).maybeSingle();
    if(error||!p){msg('login-message','Your account is verified, but the profile is incomplete. Please contact ChikChik.');return}
    profile=p;$('#auth-view').hidden=true;$('#dashboard-view').hidden=false;$('#account-name').textContent=(p.full_name||'Chik').split(' ')[0];$('#account-handle').textContent=`@${p.username} · ${p.email}`;setupProfile(p);
    scheduleIdle(()=>{loadOrders();loadRewards()},0);
  })().finally(()=>{dashboardPromise=null});
  return dashboardPromise;
}
function setupProfile(p){const f=$('#profile-form');for(const k of ['full_name','username','email','phone','division','district','street_address'])if(f.elements[k])f.elements[k].value=p[k]||'';setupHierarchy('profile-upazila','profile-union',p.upazila,p.union_name||'')}
$('#profile-form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.id=user.id;d.email=profile.email;d.phone=normalizePhone(d.phone);const {data,error}=await sb.from('profiles').update({full_name:d.full_name,username:d.username,phone:d.phone,division:'Dhaka',district:'Dhaka',upazila:d.upazila,union_name:d.union_name||null,street_address:d.street_address}).eq('id',user.id).select().single();if(error){msg('profile-message',safeDataError(error));return}profile=data;msg('profile-message','Profile and delivery address saved.',true);await loadOrders()};
async function loadOrders(){const {data,error}=await sb.from('orders').select('id,order_code,items,subtotal,delivery_charge,total,status,created_at,updated_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(50);$('#account-orders').innerHTML=error?'<div class="empty">Could not load order history.</div>':(data||[]).length?(data||[]).map(o=>`<article class="history-row"><div><strong>${esc(o.order_code)}</strong><small>${new Date(o.created_at).toLocaleString()} · ${esc(o.status.replaceAll('_',' '))}</small><p>${(o.items||[]).map(x=>`${esc(x.name)} × ${x.qty}`).join(' · ')}</p></div><div><b>${money(o.total)}</b><a class="text-btn" href="index.html#order" data-track="${esc(o.order_code)}">Track ↗</a></div></article>`).join(''):'<div class="empty">No orders linked to this account yet. Guest orders using this email or phone will appear after profile creation.</div>'}
async function loadRewards(){const {data}=await sb.from('rewards').select('reward_points,reason,created_at,order_id').eq('user_id',user.id).order('created_at',{ascending:false}).limit(50);const rows=data||[];$('#reward-total').textContent=rows.reduce((a,x)=>a+x.reward_points,0);$('#reward-list').innerHTML=rows.length?rows.slice(0,8).map(x=>`<div><span>+${x.reward_points} points</span><small>${esc(x.reason)} · ${new Date(x.created_at).toLocaleDateString()}</small></div>`).join(''):'<div class="empty">Rewards appear after an order is confirmed.</div>'}
async function uploadMedia(file,folder){const safe=file.name.replace(/[^a-z0-9._-]/gi,'-');const path=`${folder}/${user.id}/${Date.now()}-${safe}`;const {error}=await sb.storage.from('chikchik-media').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return sb.storage.from('chikchik-media').getPublicUrl(path).data.publicUrl}
$('#post-form').onsubmit=async e=>{e.preventDefault();try{const fd=new FormData(e.target),file=fd.get('media');const url=await uploadMedia(file,'user-posts');const {error}=await sb.from('content_posts').insert({author_role:'user',user_id:user.id,media_type:fd.get('media_type'),media_url:url,caption:fd.get('caption')||null,active:true});if(error)throw error;e.target.reset();msg('post-message','Your post is published.',true)}catch(err){msg('post-message','We could not publish that post. Please check the file and try again.')}};
$('#story-form').onsubmit=async e=>{e.preventDefault();try{const fd=new FormData(e.target),file=fd.get('media'),hours=Math.min(24,Math.max(1,Number(fd.get('duration')))),url=await uploadMedia(file,'user-stories');const {error}=await sb.from('content_stories').insert({author_role:'user',user_id:user.id,media_type:fd.get('media_type'),media_url:url,caption:fd.get('caption')||null,active_until:new Date(Date.now()+hours*3600000).toISOString()});if(error)throw error;e.target.reset();msg('story-message',`Story published for ${hours} hour(s).`,true)}catch(err){msg('story-message','We could not publish that story. Please check the file and try again.')}};
$('#signout').onclick=async()=>{await sb.auth.signOut();location.reload()};
function handleAuthCallbackState(session){
  if(authErrorCode){showAuthCallback('error',pendingVerificationEmail());return true}
  if(recoveryRequested()){showRecovery();return true}
  if(verificationRequested){showAuthCallback('success',pendingVerificationEmail());if(session)sb.auth.signOut({scope:'local'}).catch(()=>{});return true}
  return false;
}
sb.auth.onAuthStateChange((event,s)=>{if(event==='PASSWORD_RECOVERY'||recoveryRequested()){showRecovery();return}if(verificationRequested||authErrorCode){handleAuthCallbackState(s);return}if(s&&!user)loadDashboard(s.user)});
sb.auth.getSession().then(({data})=>{if(handleAuthCallbackState(data.session))return;if(data.session)loadDashboard(data.session.user)}).catch(()=>{if(!verificationRequested&&!recoveryRequested())msg('login-message','We could not restore your session. Please sign in again.')});
let signupStep=1;const stepNames=['Your email','Your name','Account details','Delivery address'];function showSignupStep(n){signupStep=Math.max(1,Math.min(4,n));document.querySelectorAll('.signup-step').forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===signupStep));document.querySelectorAll('.signup-step-dot').forEach((d,i)=>{d.classList.toggle('active',i===signupStep-1);d.classList.toggle('complete',i<signupStep-1)});const label=$('#signup-step-label');if(label)label.textContent=`Step ${signupStep} of 4 · ${stepNames[signupStep-1]}`;const current=document.querySelector(`.signup-step[data-step="${signupStep}"]`);if(!$('#signup-form')?.hidden)current?.querySelector('input,select,textarea')?.focus({preventScroll:true})};function validStep(n){const step=document.querySelector(`.signup-step[data-step="${n}"]`);if(!step)return true;for(const field of step.querySelectorAll('input,select,textarea')){if(!field.checkValidity()){field.reportValidity();return false}}if(n===3){const phone=normalizePhone(step.querySelector('[name="phone"]')?.value);if(!/^01\d{9}$/.test(phone)){msg('signup-message','Enter a valid Bangladesh mobile number, such as 01XXXXXXXXX.');step.querySelector('[name="phone"]')?.focus();return false}}msg('signup-message','');return true}document.querySelectorAll('.step-next').forEach(b=>b.onclick=()=>{if(validStep(signupStep)&&signupStep<4)showSignupStep(signupStep+1)});document.querySelectorAll('.step-back').forEach(b=>b.onclick=()=>{if(signupStep>1)showSignupStep(signupStep-1)});showSignupStep(1);const initialAuth=new URLSearchParams(location.search).get('mode');if(initialAuth==='signup')showAuth('signup',false);
$('#forgot-password').onclick=async()=>{const email=cleanEmail($('#login-email')?.value);const input=$('#login-email');if(!email||!input?.checkValidity()){msg('login-message','Enter your email first, then choose forgot password.');input?.focus();return}const button=$('#forgot-password');button.disabled=true;button.textContent='Sending…';try{const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:window.chikchikAuthUrl('account.html?mode=login')});msg('login-message',error?'We could not send a reset link. Please try again later.':'If an account uses that email, a password reset link has been sent.',!error)}catch{msg('login-message','We could not send a reset link. Please try again later.')}finally{button.disabled=false;button.textContent='Forgot password?'}};
$('#recovery-form').onsubmit=async e=>{e.preventDefault();const form=e.target,d=Object.fromEntries(new FormData(form));if(!form.checkValidity()){form.reportValidity();return}if(d.password!==d.confirm_password){msg('recovery-message','The passwords do not match.');return}setBusy(form,true,'Updating…');try{const {error}=await sb.auth.updateUser({password:d.password});if(error){msg('recovery-message',safeAuthError(error));return}await sb.auth.signOut();showAuth('login');msg('login-message','Password updated. You can now sign in.',true)}catch(error){msg('recovery-message',safeAuthError(error))}finally{setBusy(form,false)}};
const authCanvas=$('.auth-brand-panel');if(authCanvas&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){let frame=0,px=.5,py=.5;const paint=()=>{frame=0;authCanvas.style.setProperty('--glow-x',`${px*100}%`);authCanvas.style.setProperty('--glow-y',`${py*100}%`);authCanvas.style.setProperty('--tilt-x',`${(py-.5)*-18}`);authCanvas.style.setProperty('--tilt-y',`${(px-.5)*18}`)};authCanvas.addEventListener('pointermove',e=>{const r=authCanvas.getBoundingClientRect();px=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));py=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));if(!frame)frame=requestAnimationFrame(paint)},{passive:true});authCanvas.addEventListener('pointerleave',()=>{px=.5;py=.5;if(!frame)frame=requestAnimationFrame(paint)},{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden){authCanvas.style.setProperty('--tilt-x','0');authCanvas.style.setProperty('--tilt-y','0')}})}
