const {createClient}=window.supabase;const sb=createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);let user=null,profile=null;
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=n=>`৳${Number(n||0).toLocaleString('en-BD')}`;
const normalizePhone=p=>{let v=String(p||'').replace(/[^0-9+]/g,'').replace(/^\+/, '');if(v.startsWith('00880'))v=v.slice(4);if(v.startsWith('8801'))v=v.slice(2);return v};
const hierarchy={'Dhaka North City Corporation':['Ward 1–10','Ward 11–20','Ward 21–30','Uttara','Sector 1','Sector 3','Sector 4','Sector 7','Sector 9','Sector 11','Sector 12','Sector 13','Sector 14','Airport','Diabari','Mirpur','Pallabi','Rupnagar','Gulshan','Banani','Badda','Mohakhali','Mohammadpur','Adabor','Shyamoli','Bashundhara'],'Dhaka South City Corporation':['Ward 1–10','Ward 11–20','Ward 21–30','Dhanmondi','Kalabagan','Hazaribagh','Khilgaon','Mugdapara','Jatrabari','Dania','Motijheel','Paltan','Lalbagh','Wari','Sutrapur'],Dhamrai:['Amta','Balia','Bhararia','Dhamrai','Gangutia','Jadabpur','Kulla','Mahmudabad','Nannar','Rowail','Sanora','Sutipara'],Dohar:['Bilaspur','Kusumhati','Mahmudpur','Muksudpur','Narayanganpur','Nayabari','Raipara','Sutarpara'],Keraniganj:['Aganagar','Basta','Hazratpur','Kalatiya','Kalindi','Konda','Ruhitpur','Sakta','Subhadya','Taranagar','Tegharia'],Nawabganj:['Agla','Bakshanagar','Bandura','Barrah','Churain','Galimpur','Jantrail','Joykrishnapur','Kalakopa','Khalpar','Nayansree','Shikaripara'],Savar:['Aminbazar','Ashulia','Banagram','Bongaon','Dhamsona','Kaundia','Pathalia','Savar','Shimulia','Tetuljhora','Vakurta','Yearpur']};
function setupHierarchy(upId,unionId,selectedUp='',selectedUnion=''){const up=$(`#${upId}`),un=$(`#${unionId}`);if(!up)return;up.innerHTML='<option value="">Upazila / city corporation</option>'+Object.keys(hierarchy).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');up.value=selectedUp||'';const fill=()=>{un.innerHTML='<option value="">Union / ward / local area</option>'+((hierarchy[up.value]||[]).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join(''));un.value=selectedUnion||''};up.onchange=fill;fill()}
function msg(id,text,ok=false){const el=$(`#${id}`);el.textContent=text;el.className='form-message '+(ok?'ok':'error')}
function showAuth(tab){const signup=tab==='signup';$('#login-form').hidden=signup;$('#signup-form').hidden=!signup;document.querySelectorAll('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.authTab===tab));}
document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>showAuth(b.dataset.authTab));setupHierarchy('account-upazila','account-union');
$('#signup-form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const phone=normalizePhone(d.phone);const check=await sb.rpc('is_phone_available',{p_phone:phone});if(check.error||check.data===false){msg('signup-message','That phone number is already linked to an account.');return}const {data,error}=await sb.auth.signUp({email:d.email.trim().toLowerCase(),password:d.password,options:{data:{full_name:d.full_name,username:d.username,phone,upazila:d.upazila,union_name:d.union_name||'',street_address:d.street_address}}});if(error){msg('signup-message',error.message);return}if(!data.user){msg('signup-message','Please check your email to verify the account, then sign in.',true);return}if(data.session){const {error:pe}=await sb.from('profiles').upsert({id:data.user.id,email:data.user.email,phone,full_name:d.full_name,username:d.username,division:'Dhaka',district:'Dhaka',upazila:d.upazila,union_name:d.union_name||null,street_address:d.street_address});if(pe){msg('signup-message',pe.message);return}await loadDashboard(data.session.user);msg('signup-message','Account created.',true)}else msg('signup-message','Account created. Check your email to verify it, then sign in.',true)};
$('#login-form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const {data,error}=await sb.auth.signInWithPassword({email:d.email,password:d.password});if(error){msg('login-message','Sign in failed. Check your email and password.');return}await loadDashboard(data.user)};
async function loadDashboard(u){user=u;await sb.rpc('claim_guest_orders_for_user');const {data:p,error}=await sb.from('profiles').select('*').eq('id',u.id).maybeSingle();if(error||!p){msg('login-message','Your account is verified, but the profile is incomplete. Please contact ChikChik.');return}profile=p;$('#auth-view').hidden=true;$('#dashboard-view').hidden=false;$('#account-name').textContent=p.full_name.split(' ')[0];$('#account-handle').textContent=`@${p.username} · ${p.email}`;setupProfile(p);await Promise.all([loadOrders(),loadRewards()])}
function setupProfile(p){const f=$('#profile-form');for(const k of ['full_name','username','email','phone','division','district','street_address'])if(f.elements[k])f.elements[k].value=p[k]||'';setupHierarchy('profile-upazila','profile-union',p.upazila,p.union_name||'')}
$('#profile-form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.id=user.id;d.email=profile.email;d.phone=normalizePhone(d.phone);const {data,error}=await sb.from('profiles').update({full_name:d.full_name,username:d.username,phone:d.phone,division:'Dhaka',district:'Dhaka',upazila:d.upazila,union_name:d.union_name||null,street_address:d.street_address}).eq('id',user.id).select().single();if(error){msg('profile-message',error.message);return}profile=data;msg('profile-message','Profile and delivery address saved.',true);await loadOrders()};
async function loadOrders(){const {data,error}=await sb.from('orders').select('id,order_code,items,subtotal,delivery_charge,total,status,created_at,updated_at').eq('user_id',user.id).order('created_at',{ascending:false});$('#account-orders').innerHTML=error?'<div class="empty">Could not load order history.</div>':(data||[]).length?(data||[]).map(o=>`<article class="history-row"><div><strong>${esc(o.order_code)}</strong><small>${new Date(o.created_at).toLocaleString()} · ${esc(o.status.replaceAll('_',' '))}</small><p>${(o.items||[]).map(x=>`${esc(x.name)} × ${x.qty}`).join(' · ')}</p></div><div><b>${money(o.total)}</b><a class="text-btn" href="index.html#order" data-track="${esc(o.order_code)}">Track ↗</a></div></article>`).join(''):'<div class="empty">No orders linked to this account yet. Guest orders using this email or phone will appear after profile creation.</div>'}
async function loadRewards(){const {data}=await sb.from('rewards').select('reward_points,reason,created_at,order_id').eq('user_id',user.id).order('created_at',{ascending:false});const rows=data||[];$('#reward-total').textContent=rows.reduce((a,x)=>a+x.reward_points,0);$('#reward-list').innerHTML=rows.length?rows.slice(0,8).map(x=>`<div><span>+${x.reward_points} points</span><small>${esc(x.reason)} · ${new Date(x.created_at).toLocaleDateString()}</small></div>`).join(''):'<div class="empty">Rewards appear after an order is confirmed.</div>'}
async function uploadMedia(file,folder){const safe=file.name.replace(/[^a-z0-9._-]/gi,'-');const path=`${folder}/${user.id}/${Date.now()}-${safe}`;const {error}=await sb.storage.from('chikchik-media').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return sb.storage.from('chikchik-media').getPublicUrl(path).data.publicUrl}
$('#post-form').onsubmit=async e=>{e.preventDefault();try{const fd=new FormData(e.target),file=fd.get('media');const url=await uploadMedia(file,'user-posts');const {error}=await sb.from('content_posts').insert({author_role:'user',user_id:user.id,media_type:fd.get('media_type'),media_url:url,caption:fd.get('caption')||null,active:true});if(error)throw error;e.target.reset();msg('post-message','Your post is published.',true)}catch(err){msg('post-message',err.message)}};
$('#story-form').onsubmit=async e=>{e.preventDefault();try{const fd=new FormData(e.target),file=fd.get('media'),hours=Math.min(24,Math.max(1,Number(fd.get('duration')))),url=await uploadMedia(file,'user-stories');const {error}=await sb.from('content_stories').insert({author_role:'user',user_id:user.id,media_type:fd.get('media_type'),media_url:url,caption:fd.get('caption')||null,active_until:new Date(Date.now()+hours*3600000).toISOString()});if(error)throw error;e.target.reset();msg('story-message',`Story published for ${hours} hour(s).`,true)}catch(err){msg('story-message',err.message)}};
$('#signout').onclick=async()=>{await sb.auth.signOut();location.reload()};sb.auth.onAuthStateChange((_event,s)=>{if(s&&!user)loadDashboard(s.user)});sb.auth.getSession().then(({data})=>{if(data.session)loadDashboard(data.session.user)});
let signupStep=1;const stepNames=['Your email','Your name','Account details','Delivery address'];function showSignupStep(n){signupStep=n;document.querySelectorAll('.signup-step').forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===n));document.querySelectorAll('.signup-step-dot').forEach((d,i)=>d.classList.toggle('active',i<n));const label=$('#signup-step-label');if(label)label.textContent=`Step ${n} of 4 · ${stepNames[n-1]}`};function validStep(n){const step=document.querySelector(`.signup-step[data-step="${n}"]`);if(!step)return true;for(const field of step.querySelectorAll('input,select,textarea'))if(!field.checkValidity()){field.reportValidity();return false}return true}document.querySelectorAll('.step-next').forEach(b=>b.onclick=()=>{if(validStep(signupStep)&&signupStep<4)showSignupStep(signupStep+1)});document.querySelectorAll('.step-back').forEach(b=>b.onclick=()=>{if(signupStep>1)showSignupStep(signupStep-1)});showSignupStep(1);
