const sb=window.createChikClient();let menu=[],cart=(()=>{try{return JSON.parse(localStorage.getItem('chikchik-cart')||'[]')}catch{return[]}})(),activeCategory='All',lastTracked=null,deliveryCharge=60,currentUser=null,currentProfile=null;
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=n=>`৳${Number(n||0).toLocaleString('en-BD')}`;const normalizePhone=p=>{let v=String(p||'').replace(/[^0-9+]/g,'').replace(/^\+/, '');if(v.startsWith('00880'))v=v.slice(4);if(v.startsWith('8801'))v=v.slice(2);return v};
const dhakaHierarchy={'Dhaka North City Corporation':['Ward 1–10','Ward 11–20','Ward 21–30','Uttara','Sector 1','Sector 3','Sector 4','Sector 7','Sector 9','Sector 11','Sector 12','Sector 13','Sector 14','Airport','Diabari','Mirpur','Pallabi','Rupnagar','Gulshan','Banani','Badda','Mohakhali','Mohammadpur','Adabor','Shyamoli','Bashundhara'],'Dhaka South City Corporation':['Ward 1–10','Ward 11–20','Ward 21–30','Dhanmondi','Kalabagan','Hazaribagh','Khilgaon','Mugdapara','Jatrabari','Dania','Motijheel','Paltan','Lalbagh','Wari','Sutrapur'],Dhamrai:['Amta','Balia','Bhararia','Dhamrai','Gangutia','Jadabpur','Kulla','Mahmudabad','Nannar','Rowail','Sanora','Sutipara'],Dohar:['Bilaspur','Kusumhati','Mahmudpur','Muksudpur','Narayanganpur','Nayabari','Raipara','Sutarpara'],Keraniganj:['Aganagar','Basta','Hazratpur','Kalatiya','Kalindi','Konda','Ruhitpur','Sakta','Subhadya','Taranagar','Tegharia'],Nawabganj:['Agla','Bakshanagar','Bandura','Barrah','Churain','Galimpur','Jantrail','Joykrishnapur','Kalakopa','Khalpar','Nayansree','Shikaripara'],Savar:['Aminbazar','Ashulia','Banagram','Bongaon','Dhamsona','Kaundia','Pathalia','Savar','Shimulia','Tetuljhora','Vakurta','Yearpur']};
function fillAreas(selectedUp='',selectedUnion=''){const up=$('#upazila'),un=$('#union_name');if(!up)return;up.innerHTML='<option value="">Upazila / city corporation</option>'+Object.keys(dhakaHierarchy).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');up.value=selectedUp||'';const fill=()=>{un.innerHTML='<option value="">Union / ward / local area</option>'+((dhakaHierarchy[up.value]||[]).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join(''));un.value=selectedUnion||''};up.onchange=fill;fill()}
function renderTabs(){const cats=['All',...new Set(menu.map(x=>x.category))];$('#category-tabs').innerHTML=cats.map(c=>`<button class="tab ${c===activeCategory?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;renderTabs();renderMenu()})}
function productImage(x){const verified=x?.image_verified&&(x.image_url||x.gallery_urls?.[0]);return esc(assetUrl(verified?(x.image_url||x.gallery_urls?.[0]):'food-placeholder.svg'))}
function renderMenu(){const list=activeCategory==='All'?menu:menu.filter(x=>x.category===activeCategory);$('#menu-grid').innerHTML=list.length?list.map(x=>`<article class="menu-card" data-product-id="${x.id}"><div class="menu-image"><img loading="lazy" decoding="async" src="${productImage(x)}" alt="${esc(x.name)}"><span class="menu-category">${esc(x.category)}</span>${Number(x.popularity_score||0)>0?'<b class="best-badge">BEST SELLER</b>':''}</div><div class="menu-meta"><div><h3>${esc(x.name)}</h3><p>${esc(x.description||'Freshly made at ChikChik.')}</p></div><strong>${money(x.price)}</strong></div><button class="add-btn" data-id="${x.id}">Add to order +</button></article>`).join(''):'<div class="empty wide">Menu is being refreshed. Please check back shortly.</div>';document.querySelectorAll('.menu-card').forEach(c=>c.onclick=e=>{if(!e.target.closest('.add-btn'))location.href=`product.html?id=${encodeURIComponent(c.dataset.productId)}`});document.querySelectorAll('.add-btn').forEach(b=>b.onclick=e=>{e.stopPropagation();addToCart(b.dataset.id)})}
function renderCollection(){const rows=[...menu].sort((a,b)=>Number(b.popularity_score||0)-Number(a.popularity_score||0)).slice(0,8);$('#collection-grid').innerHTML=rows.map(x=>`<a class="collection-card" href="product.html?id=${encodeURIComponent(x.id)}" aria-label="Open ${esc(x.name)} details"><img loading="lazy" decoding="async" src="${productImage(x)}" alt="${esc(x.name)}"><span>${esc(x.name)}</span></a>`).join('')||'<div class="empty">Collection is being refreshed.</div>'}
function addToCart(id,qty=1){const item=menu.find(x=>x.id===id),found=cart.find(x=>x.id===id);if(!item)return;if(found)found.qty+=qty;else cart.push({...item,qty});renderCart();$('#order').scrollIntoView({behavior:'smooth'})}
function cartTotals(items=cart){const subtotal=items.reduce((a,x)=>a+Number(x.price)*Number(x.qty),0);return{subtotal,charge:deliveryCharge,total:subtotal+deliveryCharge}}
function renderCart(){const box=$('#cart-box');if(!cart.length){localStorage.removeItem('chikchik-cart');box.innerHTML='<div class="empty">Your cart is waiting for its first chik.<br><a class="btn dark small" href="menu.html">Browse full menu ↗</a></div>';return}localStorage.setItem('chikchik-cart',JSON.stringify(cart));const t=cartTotals();box.innerHTML=cart.map(x=>`<div class="cart-row"><span>${esc(x.name)} × ${x.qty}</span><strong>${money(x.price*x.qty)} <button class="remove" data-id="${x.id}" aria-label="Remove">×</button></strong></div>`).join('')+`<div class="cart-total"><span>Subtotal</span><strong>${money(t.subtotal)}</strong></div><div class="cart-total muted"><span>Delivery inside Dhaka</span><span>${money(t.charge)}</span></div><div class="cart-total grand"><span>Total</span><strong>${money(t.total)}</strong></div><a class="btn dark" href="checkout.html">Continue to checkout ↗</a>`;document.querySelectorAll('.remove').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==b.dataset.id);renderCart()})}
function renderOffers(rows){const box=$('#offer-list');if(!rows.length){box.innerHTML='<div class="offer-empty"><span class="offer-icon">✦</span><div><b>No active offer right now.</b><p>We keep the menu honest. Check back for the next ChikChik drop.</p></div><a class="btn dark" href="#collection">See popular chiks ↘</a></div>';return}box.innerHTML=rows.map(o=>`<button class="offer-card" data-offer="${o.id}">${o.offer_image_url?`<img class="offer-thumb" src="${esc(o.offer_image_url)}" alt="">`:'<span class="offer-icon">%</span>'}<span><small>LIMITED DROP${o.discount_percent?` · ${esc(o.discount_percent)}% OFF`:''}</small><strong>${esc(o.title)}</strong><em>${esc(o.highlight)}</em></span><b>View details ↗</b></button>`).join('');document.querySelectorAll('[data-offer]').forEach(b=>b.onclick=()=>{const o=rows.find(x=>x.id===b.dataset.offer);showModal(`${o.offer_image_url?`<img class="offer-modal-image" src="${esc(o.offer_image_url)}" alt="">`:''}<p class="section-label">Limited drop${o.discount_percent?` · ${esc(o.discount_percent)}% off`:''}</p><h2>${esc(o.title)}</h2><p>${esc(o.details)}</p>${o.terms?`<p class="modal-terms">${esc(o.terms)}</p>`:''}${o.valid_until?`<p class="modal-terms">Valid until ${esc(o.valid_until)}</p>`:''}`)})}
function showModal(html){const root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal"><button class="modal-close" data-modal-close>×</button>${html}</div></div>`;const back=root.querySelector('.modal-backdrop');back.addEventListener('click',e=>{if(e.target===back)back.remove()});back.querySelector('[data-modal-close]').onclick=()=>back.remove()}
function showProduct(x){if(!x)return;const imgs=x.image_verified?[...(x.gallery_urls||[]),x.image_url].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i):[];const gallery=imgs.length?imgs:['food-placeholder.svg'];showModal(`<div class="product-detail"><div class="product-gallery"><img id="product-main-image" src="${esc(gallery[0])}" alt="${esc(x.name)}">${gallery.length>1?`<div class="gallery-thumbs">${gallery.map((u,i)=>`<button data-gallery="${esc(u)}" class="${i===0?'active':''}"><img src="${esc(u)}" alt=""></button>`).join('')}</div>`:''}${x.video_url?`<video controls preload="metadata" src="${esc(x.video_url)}"></video>`:''}</div><div class="product-copy"><p class="section-label">${esc(x.category)}</p><h2>${esc(x.name)}</h2><strong class="product-price">${money(x.price)}</strong><p>${esc(x.description||'Freshly made at ChikChik.')}</p>${x.ingredients?`<div class="detail-block"><b>Ingredients</b><p>${esc(x.ingredients)}</p></div>`:''}${x.specifications?`<div class="detail-block"><b>Specifications</b><p>${esc(x.specifications)}</p></div>`:''}<div class="product-buy"><label>Quantity <input id="product-qty" type="number" min="1" max="20" value="1"></label><button id="product-add" class="btn red">Add to cart ↗</button></div></div><div class="product-reviews"><div class="product-review-heading"><div><p class="section-label">Member reviews</p><h3>How it tastes</h3></div><span id="product-rating"></span></div><div id="product-review-list" class="product-review-list">Loading reviews…</div>${currentUser?`<form id="product-review-form" class="review-form"><select name="rating" required><option value="">Star rating</option><option value="5">★★★★★ · 5</option><option value="4">★★★★ · 4</option><option value="3">★★★ · 3</option><option value="2">★★ · 2</option><option value="1">★ · 1</option></select><textarea name="review_text" required placeholder="Share your experience with this product"></textarea><button class="btn dark">Submit review</button></form>`:`<p class="login-review">Please <a href="account.html">create an account and sign in</a> to review this product.</p>`}</div></div>`);document.querySelectorAll('[data-gallery]').forEach(b=>b.onclick=()=>{$('#product-main-image').src=b.dataset.gallery;document.querySelectorAll('[data-gallery]').forEach(t=>t.classList.remove('active'));b.classList.add('active')});$('#product-add').onclick=()=>{addToCart(x.id,Math.max(1,Number($('#product-qty').value||1)));$('#modal-root').innerHTML=''};loadProductReviews(x.id);const form=$('#product-review-form');if(form)form.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(form));const {error}=await sb.from('product_reviews').upsert({product_id:x.id,user_id:currentUser.id,rating:Number(d.rating),review_text:d.review_text},{onConflict:'product_id,user_id'});if(error)form.insertAdjacentHTML('beforeend',`<small class="error">${esc(error.message)}</small>`);else showProduct(x)}}
async function loadProductReviews(id){const {data,error}=await sb.rpc('get_product_reviews',{p_product_id:id});const rows=data||[];const avg=rows.length?rows.reduce((a,x)=>a+x.rating,0)/rows.length:0;if($('#product-rating'))$('#product-rating').textContent=rows.length?`${avg.toFixed(1)} ★ · ${rows.length} review(s)`:'No reviews yet';if($('#product-review-list'))$('#product-review-list').innerHTML=error?'<div class="empty">Reviews are temporarily unavailable.</div>':rows.length?rows.map(x=>`<article><strong>${esc(x.username||'ChikChik member')}</strong><span>${'★'.repeat(x.rating)}${'☆'.repeat(5-x.rating)}</span><p>${esc(x.review_text)}</p></article>`).join(''):'<div class="empty">Be the first member to review this dish.</div>'}
function renderSocial(profiles,posts){$('#social-profiles').innerHTML=profiles.map(x=>`<a class="social-profile ${x.platform}" href="${esc(x.profile_url)}" target="_blank"><div class="social-cover" style="background-image:url('${esc(x.cover_image_url||'facebook-cover.jpg')}')"></div><div class="social-body"><img src="${esc(x.profile_image_url||'logo.jpg')}" alt=""><div><small>${x.platform==='instagram'?'Instagram':'Facebook'}</small><h3>${esc(x.display_name)}</h3><p>${esc(x.bio||'')}</p><strong>${esc(x.followers||'')} <span>·</span> ${esc(x.following||'')} ↗</strong></div></div></a>`).join('');$('#social-posts').innerHTML=posts.slice(0,6).map(p=>`<a class="post" href="${esc(p.post_url||'#')}" target="_blank"><img loading="lazy" decoding="async" src="${esc(assetUrl(p.image_url))}" alt="${esc(p.caption||'ChikChik post')}"><span>${esc(p.platform)} ↗</span></a>`).join('')}
function mediaCard(p){const media=p.media_type==='image'?`<img loading="lazy" decoding="async" src="${esc(assetUrl(p.media_url))}" alt="${esc(p.caption||'ChikChik community post')}">`:`<video loading="lazy" src="${esc(assetUrl(p.media_url))}" muted controls preload="metadata"></video>`;return`<article class="content-card">${media}<div><small>${p.author_role==='admin'?'CHIKCHIK':'COMMUNITY'} · ${esc(p.media_type.replace('_',' '))}</small><p>${esc(p.caption||'')}</p></div></article>`}
function renderContent(posts,stories){$('#content-grid').innerHTML=posts.length?posts.slice(0,12).map(mediaCard).join(''):'<div class="empty">No community posts yet.</div>';$('#story-strip').innerHTML=stories.length?stories.map(s=>`<article class="story-bubble"><div>${s.media_type==='image'?`<img src="${esc(s.media_url)}" alt="">`:`<video src="${esc(s.media_url)}" muted></video>`}</div><span>${s.author_role==='admin'?'ChikChik':'Member'}</span></article>`).join(''):'<div class="empty">New stories appear here for up to 24 hours.</div>'}
function renderReviews(rows){const avg=rows.length?rows.reduce((a,x)=>a+x.rating,0)/rows.length:0;$('#rating-summary').innerHTML=`<strong>${avg.toFixed(1)}</strong><span>★★★★★</span><small>Curated public reviews<br>Google Maps</small>`;$('#review-grid').innerHTML=rows.slice(0,6).map(x=>`<article class="review-card"><div class="stars">${'★'.repeat(Number(x.rating||0))}${'☆'.repeat(5-Number(x.rating||0))}</div><p>“${esc(x.review_text)}”</p><footer><strong>${esc(x.author)}</strong><span>Google Maps · ${x.rating}/5</span></footer></article>`).join('');const latest=rows.map(x=>x.last_synced_at).sort().pop();$('#review-sync').textContent=latest?new Date(latest).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'not yet'}
function statusSteps(status){const steps=[['pending','Order received'],['confirmed','Approved by ChikChik'],['preparing','Food preparing'],['packaging','Packed'],['ready','Ready'],['out_for_delivery','Out for delivery'],['delivered','Delivered']];const ix=steps.findIndex(x=>x[0]===status);return steps.map((x,i)=>`<li class="${i<=ix?'done':''} ${x[0]===status?'current':''}"><i>${i<=ix?'✓':i+1}</i><span>${x[1]}</span></li>`).join('')}
function summaryLines(o){return`<div class="summary-lines">${(o.items||[]).map(x=>`<div><span>${esc(x.name)} × ${x.qty} <small>(${money(x.price)} each)</small></span><strong>${money(x.price*x.qty)}</strong></div>`).join('')}<div><span>Subtotal</span><strong>${money(o.subtotal)}</strong></div><div><span>Delivery charge</span><strong>${money(o.delivery_charge)}</strong></div><div class="grand"><span>Total</span><strong>${money(o.total)}</strong></div></div>`}
function copyText(value,button){const done=()=>{if(button){const old=button.textContent;button.textContent='Copied ✓';setTimeout(()=>button.textContent=old,1800)}};if(navigator.clipboard?.writeText)navigator.clipboard.writeText(value).then(done).catch(()=>fallback());else fallback();function fallback(){const ta=document.createElement('textarea');ta.value=value;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();done()}}
document.addEventListener('click',e=>{const b=e.target.closest('.copy-btn');if(b)copyText(b.dataset.copy,b)});
function renderTracked(o){lastTracked=o;$('#tracking-result').innerHTML=`<div class="tracking-card"><div class="tracking-top"><div><small>TRACKING ID</small><strong>${esc(o.order_code)}</strong></div><button class="copy-btn" data-copy="${esc(o.order_code)}">Copy ID</button></div><p class="tracking-state">${esc(o.status.replaceAll('_',' '))}</p><ol class="status-steps">${statusSteps(o.status)}</ol>${summaryLines(o)}<small class="updated">Updated ${new Date(o.updated_at||o.created_at).toLocaleString()}</small></div>`}
function confirmation(payload){return`<div class="success"><div><p>Order received — thank you!</p><strong>Your tracking ID: ${esc(payload.order_code)}</strong><button class="copy-btn" data-copy="${esc(payload.order_code)}">Copy ID</button></div><p class="success-note">Save this ID to check your live order status anytime.</p>${summaryLines(payload)}<a href="#order">Track below ↘</a></div>`}
async function loadProfileForOrder(){if(!currentUser)return;const {data}=await sb.from('profiles').select('full_name,email,phone,upazila,union_name,street_address').eq('id',currentUser.id).maybeSingle();if(!data)return;currentProfile=data;const f=$('#order-form');for(const k of ['name','phone','email'])if(f.elements[k])f.elements[k].value=k==='name'?data.full_name:data[k];if(f.elements.upazila){fillAreas(data.upazila,data.union_name||'');f.elements.area.value=data.union_name||'';f.elements.address.value=data.street_address||''}}
$('#order-form').onsubmit=async e=>{
  e.preventDefault();if(!cart.length){$('#order-message').textContent='Add at least one item first.';return}
  const d=Object.fromEntries(new FormData(e.target));d.email=String(d.email||'').trim().toLowerCase();d.phone=normalizePhone(d.phone);
  const {data,error}=await sb.rpc('create_order',{p_name:d.name,p_email:d.email,p_phone:d.phone,p_division:d.division,p_district:d.district,p_upazila:d.upazila,p_union_name:d.union_name||'',p_area:d.area,p_address:d.address,p_items:cart.map(x=>({id:x.id,qty:Math.max(1,Math.min(20,Number(x.qty||1)))}))});
  const order=data?.[0];if(error||!order){$('#order-message').textContent=error?.message||'We could not submit your order. Please check your details.';return}
  localStorage.setItem('chikchik-last-order',order.order_code);localStorage.setItem('chikchik-last-order-verifier',d.phone);sessionStorage.setItem('chikchik-last-order-verifier',d.phone);cart=[];renderCart();e.target.reset();fillAreas();$('#order-message').innerHTML=confirmation(order);$('#tracking-form input[name="code"]').value=order.order_code;$('#tracking-form input[name="verifier"]').value=d.phone;track(order.order_code,d.phone)
};
async function track(code,verifier){const {data,error}=await sb.rpc('get_order_by_code',{p_code:code,p_verifier:verifier||null});if(error||!data?.length){$('#tracking-result').innerHTML='<div class="empty">No order found. Enter the exact phone or email used for this order.</div>';return}renderTracked(data[0])}
async function revealAdminLink(){const link=$('#admin-footer-link');if(!link||!currentUser){if(link)link.hidden=true;return}const {data}=await sb.rpc('is_admin');link.hidden=!Boolean(data)}
sb.auth.getSession().then(({data})=>{currentUser=data.session?.user||null;if(currentUser)loadProfileForOrder();revealAdminLink()});sb.auth.onAuthStateChange((_event,s)=>{currentUser=s?.user||null;if(currentUser)loadProfileForOrder();revealAdminLink()});sb.channel('public-home-catalog').on('postgres_changes',{event:'*',schema:'public',table:'menu_items'},()=>{try{sessionStorage.removeItem('chikchik:home-menu-v2')}catch{};loadPublicOptimized()}).subscribe();sb.channel('order-tracking').on('postgres_changes',{event:'UPDATE',schema:'public',table:'orders'},payload=>{if(lastTracked&&payload.new.order_code===lastTracked.order_code)track(lastTracked.order_code,sessionStorage.getItem('chikchik-last-order-verifier')||localStorage.getItem('chikchik-last-order-verifier'))}).subscribe();sb.channel('community-feed').on('postgres_changes',{event:'*',schema:'public',table:'content_posts'},loadSecondary).subscribe();sb.channel('community-stories').on('postgres_changes',{event:'*',schema:'public',table:'content_stories'},loadSecondary).subscribe();let secondaryPromise=null;
async function loadSecondary(){
  if(secondaryPromise)return secondaryPromise;
  secondaryPromise=(async()=>{
    const results=await Promise.allSettled([
      sb.from('social_profiles').select('id,platform,profile_url,cover_image_url,profile_image_url,display_name,bio,followers,following').limit(10),
      sb.from('social_posts').select('id,platform,post_url,image_url,caption,sort_order').eq('active',true).order('sort_order').limit(12),
      sb.from('reviews').select('id,author,rating,review_text,featured,published_at,last_synced_at').order('featured',{ascending:false}).order('rating',{ascending:false}).order('published_at',{ascending:false}).limit(20),
      sb.from('content_posts').select('id,author_role,media_type,media_url,caption,created_at').eq('active',true).order('created_at',{ascending:false}).limit(12),
      sb.from('content_stories').select('id,author_role,media_type,media_url,caption,active_until,created_at').eq('active',true).gt('active_until',new Date().toISOString()).order('created_at',{ascending:false}).limit(12)
    ]);
    const rows=r=>r.status==='fulfilled'?(r.value.data||[]):[];
    const social=rows(results[0]), posts=rows(results[1]), reviews=rows(results[2]), contentPosts=rows(results[3]), stories=rows(results[4]);
    writePageCache('home-social',{social,posts});writePageCache('home-reviews',reviews);writePageCache('home-content',{contentPosts,stories});
    renderSocial(social,posts);renderReviews(reviews);renderContent(contentPosts,stories);
  })().finally(()=>{secondaryPromise=null});
  return secondaryPromise;
}
async function loadPublicOptimized(){
  const cachedMenu=readPageCache('home-menu-v2'),cachedOffers=readPageCache('home-offers');
  if(cachedMenu){menu=cachedMenu;renderTabs();renderMenu();renderCollection()}
  if(cachedOffers)renderOffers(cachedOffers);
  const results=await Promise.allSettled([
    sb.from('menu_items').select('id,name,category,price,description,image_url,gallery_urls,image_verified,image_alt_text,catalog_status,popularity_score').eq('available',true).eq('catalog_status','active').order('category').order('name').limit(100),
    sb.from('offers').select('id,title,highlight,details,terms,discount_percent,offer_image_url,valid_until').eq('active',true).order('created_at',{ascending:false}).limit(20),
    sb.from('site_settings').select('key,value').limit(20)
  ]);
  const rows=r=>r.status==='fulfilled'?(r.value.data||[]):[];
  menu=rows(results[0]);const offers=rows(results[1]);const settings=rows(results[2]);
  writePageCache('home-menu-v2',menu);writePageCache('home-offers',offers);
  const delivery=settings.find(x=>x.key==='delivery');deliveryCharge=Number(delivery?.value?.charge||60);
  renderTabs();renderMenu();renderCollection();renderOffers(offers);fillAreas();
  scheduleIdle(loadSecondary,150);
}
loadPublicOptimized();const saved=localStorage.getItem('chikchik-last-order'),savedVerifier=sessionStorage.getItem('chikchik-last-order-verifier')||localStorage.getItem('chikchik-last-order-verifier');if(saved){$('#tracking-form input[name="code"]').value=saved;$('#tracking-form input[name="verifier"]').value=savedVerifier||''}$('#tracking-form').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));track(String(d.code||'').trim(),String(d.verifier||'').trim())};
