-- Product catalogue provenance and duplicate-safe public visibility.
alter table public.menu_items add column if not exists slug text;
alter table public.menu_items add column if not exists catalog_status text not null default 'active';
alter table public.menu_items add column if not exists source_confidence text not null default 'unverified';
alter table public.menu_items add column if not exists source_url text;
alter table public.menu_items add column if not exists image_source_url text;
alter table public.menu_items add column if not exists image_verified boolean not null default false;
alter table public.menu_items add column if not exists image_alt_text text;
alter table public.menu_items add column if not exists source_notes text;
alter table public.menu_items add column if not exists last_verified_at timestamptz;
alter table public.menu_items drop constraint if exists menu_items_catalog_status_check;
alter table public.menu_items add constraint menu_items_catalog_status_check check (catalog_status in ('active','hidden','pending_verification'));
alter table public.menu_items drop constraint if exists menu_items_source_confidence_check;
alter table public.menu_items add constraint menu_items_source_confidence_check check (source_confidence in ('official','cross_checked','unverified'));
create unique index if not exists menu_items_slug_uidx on public.menu_items(slug) where slug is not null;
create index if not exists menu_items_catalog_status_idx on public.menu_items(catalog_status,available,category,name);
alter table public.social_posts add column if not exists menu_item_id uuid references public.menu_items(id) on delete set null;
create index if not exists social_posts_menu_item_idx on public.social_posts(menu_item_id);

update public.menu_items set image_verified=false,image_alt_text=null,source_confidence='unverified',source_url=null,image_source_url=null,last_verified_at=null;
update public.menu_items set slug='lemon-soda-pop',category='Beverages',catalog_status='active' where lower(name)='lemon soda pop';
update public.menu_items set slug='mango-soda-pop',category='Beverages',catalog_status='active' where lower(name)='mango soda pop' and price=159;
update public.menu_items set catalog_status='hidden',slug='mango-soda-pop-legacy-149' where lower(name)='mango soda pop' and price=149;
update public.menu_items set slug='three-finger-combo',catalog_status='active' where lower(name)='3 finger combo';
update public.menu_items set slug='chikster-combo',price=499,catalog_status='active',source_confidence='official',source_url='https://www.instagram.com/eatchikchik/reel/Db59wN0h1m2/',source_notes='Official Instagram search result names Chikster Combo at 499 BDT; verify against current physical/menu card before changing again.',last_verified_at=now() where lower(name)='chikster combo' and price=679;
update public.menu_items set catalog_status='hidden',slug='chikster-combo-legacy-698' where lower(name)='chikster combo' and price=698;
update public.menu_items set slug='hotchik-combo',price=549,catalog_status='active',source_confidence='official',source_url='https://www.instagram.com/eatchikchik/reel/Db59wN0h1m2/',source_notes='Official Instagram search result names HotChik Combo at 549 BDT; verify against current physical/menu card before changing again.',last_verified_at=now() where lower(name)='hotchik combo' and price=439;
update public.menu_items set catalog_status='hidden',slug='hotchik-combo-legacy-448' where lower(name)='hotchik combo' and price=448;
update public.menu_items set name='Four Finger Feast',slug='four-finger-feast',catalog_status='active',image_url='four-feast.jpg',gallery_urls=array['four-feast.jpg'],image_verified=true,image_alt_text='ChikChik Four Finger Feast with fries, toast, sauce and drink',image_source_url='https://www.facebook.com/ChikChik-61591125944196/',source_confidence='cross_checked',source_url='https://www.facebook.com/ChikChik-61591125944196/',source_notes='The branded local visual and official social caption use the same product name.',last_verified_at=now() where lower(name)='four finger combo' and price=498;
update public.menu_items set catalog_status='hidden',slug='four-finger-combo-legacy-489' where lower(name)='4 finger combo';
update public.menu_items set image_url='finger.jpg',gallery_urls=array['finger.jpg'],image_verified=true,image_alt_text='ChikChik crispy chicken finger served with signature dipping sauce',image_source_url='https://www.instagram.com/eatchikchik/',source_confidence='cross_checked',source_url='https://www.instagram.com/eatchikchik/',source_notes='Official social visual matches the chicken finger product identity.',last_verified_at=now() where lower(name)='chicken finger';
update public.menu_items set image_url='dip.jpg',gallery_urls=array['dip.jpg'],image_verified=true,image_alt_text='ChikChik signature sauce with a crispy chicken finger',image_source_url='https://www.facebook.com/ChikChik-61591125944196/',source_confidence='cross_checked',source_url='https://www.facebook.com/ChikChik-61591125944196/',source_notes='Official social snapshot is captioned Chik Sauce; used only for the signature sauce product.',last_verified_at=now() where lower(name)='chik sauce (50 ml)';
update public.menu_items set image_url=null,gallery_urls='{}',video_url=null,image_verified=false,image_alt_text=null where catalog_status='active' and lower(name) not in ('chicken finger','chik sauce (50 ml)','four finger feast');
update public.social_posts set menu_item_id=null;
update public.social_posts set menu_item_id=(select id from public.menu_items where slug='four-finger-feast') where lower(caption) like '%four finger%';
update public.social_posts set menu_item_id=(select id from public.menu_items where lower(name)='chik sauce (50 ml)' and catalog_status='active') where lower(caption)='chik sauce makes the crunch.';
update public.social_posts set menu_item_id=(select id from public.menu_items where lower(name)='chicken finger' and catalog_status='active') where lower(caption) like '%crispy to dip%';
comment on column public.menu_items.image_verified is 'True only when visual is tied to this specific product; false means neutral placeholder.';
comment on column public.menu_items.source_confidence is 'official, cross_checked, or unverified public-source confidence.';
update public.menu_items set slug=trim(both '-' from regexp_replace(lower(name),'[^a-z0-9]+','-','g')) where catalog_status='active' and slug is null;
